# UPI Shield AI — Notebook 1: Data Understanding

## Objective

The objective of this notebook is to understand the structure and quality of the PaySim online transaction fraud dataset.

In this notebook, we will:

1. Load the dataset from Google Drive.
2. Understand the number of rows and columns.
3. Study the meaning of each column.
4. Check missing values and duplicate records.
5. Analyze the target variable `isFraud`.
6. Understand transaction types.
7. Generate initial observations for the next EDA notebook.

This notebook is the first step in building the **UPI Transaction Risk Scoring System using Machine Learning**.

In [1]:
# ---------------------------------------------------------
# Step 1: Import Required Libraries
# ---------------------------------------------------------
# In this section, we import all the libraries required for
# dataset loading, basic analysis, warnings handling, and
# display formatting.

import os
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

# Display settings for better readability
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", lambda x: "%.4f" % x)

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# ---------------------------------------------------------
# Step 2: Mount Google Drive
# ---------------------------------------------------------
# We mount Google Drive so that we can access the project
# folder and dataset saved inside Google Drive.

from google.colab import drive
drive.mount('/content/drive')

print("Google Drive mounted successfully.")

Mounted at /content/drive
Google Drive mounted successfully.

In [3]:
 # ---------------------------------------------------------
# Step 3: Define Project Paths
# ---------------------------------------------------------
# BASE_DIR is the main project directory.
# RAW_DATA_DIR contains the original dataset.
# PROCESSED_DATA_DIR will store processed datasets later.
# REPORTS_DIR will store summary reports.

BASE_DIR = "/content/drive/MyDrive/UPI-Shield-AI-Transaction-Risk-Scoring"

RAW_DATA_DIR = os.path.join(BASE_DIR, "data", "raw")
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, "data", "processed")
REPORTS_DIR = os.path.join(BASE_DIR, "reports")

DATA_PATH = os.path.join(RAW_DATA_DIR, "onlinefraud.csv")

print("Base Directory:", BASE_DIR)
print("Raw Data Directory:", RAW_DATA_DIR)
print("Processed Data Directory:", PROCESSED_DATA_DIR)
print("Reports Directory:", REPORTS_DIR)
print("Dataset Path:", DATA_PATH)

Base Directory: /content/drive/MyDrive/UPI-Shield-AI-Transaction-Risk-Scoring
Raw Data Directory: /content/drive/MyDrive/UPI-Shield-AI-Transaction-Risk-Scoring/data/raw
Processed Data Directory: /content/drive/MyDrive/UPI-Shield-AI-Transaction-Risk-Scoring/data/processed
Reports Directory: /content/drive/MyDrive/UPI-Shield-AI-Transaction-Risk-Scoring/reports
Dataset Path: /content/drive/MyDrive/UPI-Shield-AI-Transaction-Risk-Scoring/data/raw/onlinefraud.csv

In [4]:
# ---------------------------------------------------------
# Step 4: Check Dataset Availability
# ---------------------------------------------------------
# Before loading the dataset, we check whether the dataset file
# exists at the expected location.

if os.path.exists(DATA_PATH):
    print("Dataset found successfully.")
    print("File path:", DATA_PATH)
else:
    print("Dataset not found.")
    print("Please check whether onlinefraud.csv is present in data/raw folder.")

Dataset found successfully.
File path: /content/drive/MyDrive/UPI-Shield-AI-Transaction-Risk-Scoring/data/raw/onlinefraud.csv

In [5]:
# ---------------------------------------------------------
# Step 5: Load Dataset
# ---------------------------------------------------------
# We load the dataset using pandas.
# The dataset is large, so loading may take some time.

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully.")
print("Dataset shape:", df.shape)

Dataset loaded successfully.
Dataset shape: (6362620, 11)

In [6]:
# ---------------------------------------------------------
# Step 6: Display First 5 Rows
# ---------------------------------------------------------
# This helps us understand how the dataset looks.

df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.6400,C1231006815,170136.0000,160296.3600,M1979787155,0.0000,0.0000,0,0
1,1,PAYMENT,1864.2800,C1666544295,21249.0000,19384.7200,M2044282225,0.0000,0.0000,0,0
2,1,TRANSFER,181.0000,C1305486145,181.0000,0.0000,C553264065,0.0000,0.0000,1,0
3,1,CASH_OUT,181.0000,C840083671,181.0000,0.0000,C38997010,21182.0000,0.0000,1,0
4,1,PAYMENT,11668.1400,C2048537720,41554.0000,29885.8600,M1230701703,0.0000,0.0000,0,0

In [7]:
# ---------------------------------------------------------
# Step 7: Display Last 5 Rows
# ---------------------------------------------------------
# This helps us verify the ending records of the dataset.

df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
6362615,743,CASH_OUT,339682.1300,C786484425,339682.1300,0.0000,C776919290,0.0000,339682.1300,1,0
6362616,743,TRANSFER,6311409.2800,C1529008245,6311409.2800,0.0000,C1881841831,0.0000,0.0000,1,0
6362617,743,CASH_OUT,6311409.2800,C1162922333,6311409.2800,0.0000,C1365125890,68488.8400,6379898.1100,1,0
6362618,743,TRANSFER,850002.5200,C1685995037,850002.5200,0.0000,C2080388513,0.0000,0.0000,1,0
6362619,743,CASH_OUT,850002.5200,C1280323807,850002.5200,0.0000,C873221189,6510099.1100,7360101.6300,1,0

## Dataset Column Description

The dataset contains online/mobile money transaction records.

| Column Name | Description |
|---|---|
| `step` | Time step of transaction. In this dataset, 1 step represents 1 hour. |
| `type` | Type of transaction such as PAYMENT, TRANSFER, CASH_OUT, CASH_IN, DEBIT. |
| `amount` | Amount involved in the transaction. |
| `nameOrig` | Customer ID of the sender/origin account. |
| `oldbalanceOrg` | Sender's balance before the transaction. |
| `newbalanceOrig` | Sender's balance after the transaction. |
| `nameDest` | Customer ID of the receiver/destination account. |
| `oldbalanceDest` | Receiver's balance before the transaction. |
| `newbalanceDest` | Receiver's balance after the transaction. |
| `isFraud` | Target column. 1 means fraudulent transaction, 0 means normal transaction. |
| `isFlaggedFraud` | Rule-based fraud flag provided in the dataset. |

In [8]:
# ---------------------------------------------------------
# Step 8: Check Column Names
# ---------------------------------------------------------
# This helps us verify all available columns in the dataset.

print("Total number of columns:", len(df.columns))
print("\nColumn names:")
for col in df.columns:
    print("-", col)

Total number of columns: 11

Column names:
- step
- type
- amount
- nameOrig
- oldbalanceOrg
- newbalanceOrig
- nameDest
- oldbalanceDest
- newbalanceDest
- isFraud
- isFlaggedFraud

In [9]:
# ---------------------------------------------------------
# Step 9: Basic Dataset Information
# ---------------------------------------------------------
# df.info() gives information about:
# 1. Number of non-null values
# 2. Data types
# 3. Memory usage

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

In [10]:
# ---------------------------------------------------------
# Step 10: Create Data Type Summary Table
# ---------------------------------------------------------
# This creates a clean summary table showing each column,
# its data type, number of unique values, and missing values.

data_summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Unique Values": df.nunique().values,
    "Missing Values": df.isnull().sum().values,
    "Missing Percentage": (df.isnull().sum().values / len(df)) * 100
})

data_summary

,Column,Data Type,Unique Values,Missing Values,Missing Percentage
0,step,int64,743,0,0.0000
1,type,object,5,0,0.0000
2,amount,float64,5316900,0,0.0000
3,nameOrig,object,6353307,0,0.0000
4,oldbalanceOrg,float64,1845844,0,0.0000
5,newbalanceOrig,float64,2682586,0,0.0000
6,nameDest,object,2722362,0,0.0000
7,oldbalanceDest,float64,3614697,0,0.0000
8,newbalanceDest,float64,3555499,0,0.0000
9,isFraud,int64,2,0,0.0000
10,isFlaggedFraud,int64,2,0,0.0000

In [11]:
# ---------------------------------------------------------
# Step 11: Check Dataset Size and Memory Usage
# ---------------------------------------------------------
# Since this is a large dataset, we check memory usage.
# This helps us understand whether optimization may be needed later.

memory_usage_mb = df.memory_usage(deep=True).sum() / (1024 ** 2)

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Memory usage: {:.2f} MB".format(memory_usage_mb))

Number of rows: 6362620
Number of columns: 11
Memory usage: 1452.57 MB

In [12]:
# ---------------------------------------------------------
# Step 12: Check Missing Values
# ---------------------------------------------------------
# Missing values can affect model training.
# Here, we check missing values column-wise.

missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": missing_percentage
})

missing_summary

                Missing Values  Missing Percentage
step                         0              0.0000
type                         0              0.0000
amount                       0              0.0000
nameOrig                     0              0.0000
oldbalanceOrg                0              0.0000
newbalanceOrig               0              0.0000
nameDest                     0              0.0000
oldbalanceDest               0              0.0000
newbalanceDest               0              0.0000
isFraud                      0              0.0000
isFlaggedFraud               0              0.0000

In [13]:
# ---------------------------------------------------------
# Step 13: Missing Value Result
# ---------------------------------------------------------
# This gives a simple message based on missing value count.

total_missing = df.isnull().sum().sum()

if total_missing == 0:
    print("No missing values found in the dataset.")
else:
    print("Total missing values found:", total_missing)

No missing values found in the dataset.

In [14]:
# ---------------------------------------------------------
# Step 14: Check Duplicate Records
# ---------------------------------------------------------
# Duplicate rows can create bias during analysis and training.
# We check the number and percentage of duplicate records.

duplicate_count = df.duplicated().sum()
duplicate_percentage = (duplicate_count / len(df)) * 100

print("Duplicate records:", duplicate_count)
print("Duplicate percentage: {:.4f}%".format(duplicate_percentage))

Duplicate records: 0
Duplicate percentage: 0.0000%

In [15]:
# ---------------------------------------------------------
# Step 15: Statistical Summary of Numerical Columns
# ---------------------------------------------------------
# This gives count, mean, standard deviation, minimum,
# maximum, and quartile values for numerical columns.

df.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6362620.0000,6362620.0000,6362620.0000,6362620.0000,6362620.0000,6362620.0000,6362620.0000,6362620.0000
mean,243.3972,179861.9035,833883.1041,855113.6686,1100701.6665,1224996.3982,0.0013,0.0000
std,142.3320,603858.2315,2888242.6730,2924048.5030,3399180.1130,3674128.9421,0.0359,0.0016
min,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,156.0000,13389.5700,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,239.0000,74871.9400,14208.0000,0.0000,132705.6650,214661.4400,0.0000,0.0000
75%,335.0000,208721.4775,107315.1750,144258.4100,943036.7075,1111909.2500,0.0000,0.0000
max,743.0000,92445516.6400,59585040.3700,49585040.3700,356015889.3500,356179278.9200,1.0000,1.0000

In [16]:
# ---------------------------------------------------------
# Step 16: Summary of Categorical Columns
# ---------------------------------------------------------
# The transaction type column is categorical.
# This cell summarizes all object/category columns.

categorical_columns = df.select_dtypes(include=["object"]).columns.tolist()

print("Categorical columns:", categorical_columns)

df[categorical_columns].describe()

Categorical columns: ['type', 'nameOrig', 'nameDest']

            type     nameOrig     nameDest
count    6362620      6362620      6362620
unique         5      6353307      2722362
top     CASH_OUT  C1530544995  C1286084959
freq     2237500            3          113

In [17]:
# ---------------------------------------------------------
# Step 17: Transaction Type Distribution
# ---------------------------------------------------------
# This shows how many transactions belong to each transaction type.

transaction_type_counts = df["type"].value_counts()

print("Transaction Type Distribution:")
print(transaction_type_counts)

Transaction Type Distribution:
type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [18]:
# ---------------------------------------------------------
# Step 18: Transaction Type Percentage
# ---------------------------------------------------------
# This shows transaction type distribution in percentage form.

transaction_type_percentage = df["type"].value_counts(normalize=True) * 100

transaction_type_summary = pd.DataFrame({
    "Transaction Count": transaction_type_counts,
    "Percentage": transaction_type_percentage
})

transaction_type_summary

          Transaction Count  Percentage
type
CASH_OUT            2237500     35.1663
PAYMENT             2151495     33.8146
CASH_IN             1399284     21.9923
TRANSFER             532909      8.3756
DEBIT                 41432      0.6512

In [19]:
# ---------------------------------------------------------
# Step 19: Target Variable Distribution
# ---------------------------------------------------------
# isFraud is our target column.
# 0 means normal transaction.
# 1 means fraud transaction.

fraud_counts = df["isFraud"].value_counts()
fraud_percentage = df["isFraud"].value_counts(normalize=True) * 100

fraud_summary = pd.DataFrame({
    "Transaction Type": ["Normal", "Fraud"],
    "Count": [fraud_counts.get(0, 0), fraud_counts.get(1, 0)],
    "Percentage": [fraud_percentage.get(0, 0), fraud_percentage.get(1, 0)]
})

fraud_summary

  Transaction Type    Count  Percentage
0           Normal  6354407     99.8709
1            Fraud     8213      0.1291

In [20]:
# ---------------------------------------------------------
# Step 20: Print Fraud Imbalance Clearly
# ---------------------------------------------------------
# This gives a clear class imbalance summary.
# Fraud detection datasets usually have very few fraud cases.

normal_count = fraud_counts.get(0, 0)
fraud_count = fraud_counts.get(1, 0)

print("Normal Transactions:", normal_count)
print("Fraud Transactions:", fraud_count)

print("\nNormal Transaction Percentage: {:.4f}%".format((normal_count / len(df)) * 100))
print("Fraud Transaction Percentage: {:.4f}%".format((fraud_count / len(df)) * 100))

imbalance_ratio = normal_count / fraud_count
print("\nClass Imbalance Ratio:")
print("For every 1 fraud transaction, there are approximately {:.0f} normal transactions.".format(imbalance_ratio))

Normal Transactions: 6354407
Fraud Transactions: 8213

Normal Transaction Percentage: 99.8709%
Fraud Transaction Percentage: 0.1291%

Class Imbalance Ratio:
For every 1 fraud transaction, there are approximately 774 normal transactions.

## Initial Observation: Class Imbalance

The dataset is highly imbalanced because fraud transactions are much fewer than normal transactions.

This is important because a model can achieve very high accuracy by predicting most transactions as normal, but such a model may fail to detect actual fraud cases.

Therefore, during model evaluation, we should focus more on:

- Precision
- Recall
- F1-score
- ROC-AUC
- Confusion Matrix

For fraud detection, recall is especially important because missing an actual fraud transaction can be costly.

In [21]:
# ---------------------------------------------------------
# Step 21: Fraud Distribution by Transaction Type
# ---------------------------------------------------------
# This table shows how many fraud transactions are present
# in each transaction type.

fraud_by_type = df.groupby("type")["isFraud"].agg(["count", "sum"])

fraud_by_type = fraud_by_type.rename(columns={
    "count": "Total Transactions",
    "sum": "Fraud Transactions"
})

fraud_by_type["Fraud Percentage"] = (
    fraud_by_type["Fraud Transactions"] / fraud_by_type["Total Transactions"]
) * 100

fraud_by_type = fraud_by_type.sort_values(by="Fraud Transactions", ascending=False)

fraud_by_type

          Total Transactions  Fraud Transactions  Fraud Percentage
type
CASH_OUT             2237500                4116            0.1840
TRANSFER              532909                4097            0.7688
CASH_IN              1399284                   0            0.0000
DEBIT                  41432                   0            0.0000
PAYMENT              2151495                   0            0.0000

In [22]:
# ---------------------------------------------------------
# Step 22: Analyze isFlaggedFraud Column
# ---------------------------------------------------------
# isFlaggedFraud is a rule-based flag in the dataset.
# We check how many transactions were flagged by this rule.

flagged_counts = df["isFlaggedFraud"].value_counts()

print("isFlaggedFraud distribution:")
print(flagged_counts)

print("\nPercentage:")
print(df["isFlaggedFraud"].value_counts(normalize=True) * 100)

isFlaggedFraud distribution:
isFlaggedFraud
0    6362604
1         16
Name: count, dtype: int64

Percentage:
isFlaggedFraud
0   99.9997
1    0.0003
Name: proportion, dtype: float64

In [23]:
# ---------------------------------------------------------
# Step 23: Compare isFraud and isFlaggedFraud
# ---------------------------------------------------------
# This helps us understand whether the rule-based flag catches
# actual fraud transactions properly.

fraud_flag_comparison = pd.crosstab(
    df["isFraud"],
    df["isFlaggedFraud"],
    rownames=["Actual Fraud"],
    colnames=["Flagged Fraud"]
)

fraud_flag_comparison

Flagged Fraud        0   1
Actual Fraud
0              6354407   0
1                 8197  16

## Observation: `isFlaggedFraud`

The column `isFlaggedFraud` is a rule-based fraud flag already present in the dataset.

However, our goal is to build a machine learning-based risk scoring system. Therefore, we should be careful while using this column during model training.

If `isFlaggedFraud` directly leaks fraud-related rule information, it may make the model look better than it actually is.

We will analyze it further before deciding whether to use or remove it in model training.

In [24]:
# ---------------------------------------------------------
# Step 24: Amount Summary for Normal vs Fraud Transactions
# ---------------------------------------------------------
# This compares transaction amount statistics for normal and
# fraud transactions.

amount_summary = df.groupby("isFraud")["amount"].describe()

amount_summary

,count,mean,std,min,25%,50%,75%,max
isFraud,,,,,,,,
0,6354407.0000,178197.0417,596236.9813,0.0100,13368.3950,74684.7200,208364.7600,92445516.6400
1,8213.0000,1467967.2991,2404252.9472,0.0000,127091.3300,441423.4400,1517771.4800,10000000.0000

In [25]:
# ---------------------------------------------------------
# Step 25: Improve Amount Summary Readability
# ---------------------------------------------------------
# We rename target labels from 0/1 to Normal/Fraud for better
# readability.

amount_summary_readable = amount_summary.copy()
amount_summary_readable.index = ["Normal Transactions", "Fraud Transactions"]

amount_summary_readable

,count,mean,std,min,25%,50%,75%,max
Normal Transactions,6354407.0000,178197.0417,596236.9813,0.0100,13368.3950,74684.7200,208364.7600,92445516.6400
Fraud Transactions,8213.0000,1467967.2991,2404252.9472,0.0000,127091.3300,441423.4400,1517771.4800,10000000.0000

In [26]:
# ---------------------------------------------------------
# Step 26: Balance Columns Summary
# ---------------------------------------------------------
# This gives statistical summary of sender and receiver balance
# columns.

balance_columns = [
    "oldbalanceOrg",
    "newbalanceOrig",
    "oldbalanceDest",
    "newbalanceDest"
]

df[balance_columns].describe()

       oldbalanceOrg  newbalanceOrig  oldbalanceDest  newbalanceDest
count   6362620.0000    6362620.0000    6362620.0000    6362620.0000
mean     833883.1041     855113.6686    1100701.6665    1224996.3982
std     2888242.6730    2924048.5030    3399180.1130    3674128.9421
min           0.0000          0.0000          0.0000          0.0000
25%           0.0000          0.0000          0.0000          0.0000
50%       14208.0000          0.0000     132705.6650     214661.4400
75%      107315.1750     144258.4100     943036.7075    1111909.2500
max    59585040.3700   49585040.3700  356015889.3500  356179278.9200

In [27]:
# ---------------------------------------------------------
# Step 27: Check Zero Balance After Transaction
# ---------------------------------------------------------
# In fraud transactions, sender balance becoming zero after
# transaction can be an important pattern.
# We check this behavior here.

zero_balance_summary = df.groupby("isFraud")["newbalanceOrig"].apply(lambda x: (x == 0).sum())

zero_balance_percentage = df.groupby("isFraud")["newbalanceOrig"].apply(lambda x: ((x == 0).sum() / len(x)) * 100)

zero_balance_result = pd.DataFrame({
    "Zero New Sender Balance Count": zero_balance_summary,
    "Zero New Sender Balance Percentage": zero_balance_percentage
})

zero_balance_result.index = ["Normal Transactions", "Fraud Transactions"]

zero_balance_result

,Zero New Sender Balance Count,Zero New Sender Balance Percentage
Normal Transactions,3601513,56.6774
Fraud Transactions,8053,98.0519

In [28]:
# ---------------------------------------------------------
# Step 28: Check Unique Sender and Receiver IDs
# ---------------------------------------------------------
# nameOrig and nameDest are customer/account identifiers.
# We check their uniqueness to understand whether they can
# be useful directly or should be removed later.

unique_sender_count = df["nameOrig"].nunique()
unique_receiver_count = df["nameDest"].nunique()

print("Unique sender IDs:", unique_sender_count)
print("Unique receiver IDs:", unique_receiver_count)

print("\nTotal transactions:", len(df))

print("\nSender uniqueness percentage: {:.2f}%".format((unique_sender_count / len(df)) * 100))
print("Receiver uniqueness percentage: {:.2f}%".format((unique_receiver_count / len(df)) * 100))

Unique sender IDs: 6353307
Unique receiver IDs: 2722362

Total transactions: 6362620

Sender uniqueness percentage: 99.85%
Receiver uniqueness percentage: 42.79%

## Observation: Sender and Receiver ID Columns

The columns `nameOrig` and `nameDest` represent sender and receiver account/customer IDs.

These columns usually have very high cardinality, meaning they contain many unique values.

For a basic machine learning pipeline, these ID columns may not be directly useful because they can make the model memorize specific account IDs instead of learning transaction behavior.

Therefore, in the feature engineering notebook, we will mostly focus on transaction behavior features such as amount, transaction type, and balance changes.

In [29]:
# ---------------------------------------------------------
# Step 29: Check Time Step Range
# ---------------------------------------------------------
# The step column represents time.
# We check the minimum and maximum step values.

print("Minimum step:", df["step"].min())
print("Maximum step:", df["step"].max())
print("Number of unique steps:", df["step"].nunique())

Minimum step: 1
Maximum step: 743
Number of unique steps: 743

In [30]:
# ---------------------------------------------------------
# Step 30: Create Dataset Quality Summary
# ---------------------------------------------------------
# This function summarizes important dataset quality details
# in one place.

def dataset_quality_summary(data):
    summary = {
        "Total Rows": data.shape[0],
        "Total Columns": data.shape[1],
        "Total Missing Values": data.isnull().sum().sum(),
        "Total Duplicate Rows": data.duplicated().sum(),
        "Fraud Transactions": data["isFraud"].sum(),
        "Normal Transactions": (data["isFraud"] == 0).sum(),
        "Fraud Percentage": (data["isFraud"].mean()) * 100,
        "Unique Transaction Types": data["type"].nunique()
    }

    return pd.DataFrame(summary.items(), columns=["Metric", "Value"])

quality_summary = dataset_quality_summary(df)
quality_summary

                     Metric        Value
0                Total Rows 6362620.0000
1             Total Columns      11.0000
2      Total Missing Values       0.0000
3      Total Duplicate Rows       0.0000
4        Fraud Transactions    8213.0000
5       Normal Transactions 6354407.0000
6          Fraud Percentage       0.1291
7  Unique Transaction Types       5.0000

In [31]:
# ---------------------------------------------------------
# Step 31: Create Initial Project Observations
# ---------------------------------------------------------
# These observations summarize what we learned from Notebook 1.
# We will save them in a report file for project documentation.

observations = []

observations.append("The dataset was loaded successfully from Google Drive.")
observations.append(f"The dataset contains {df.shape[0]} rows and {df.shape[1]} columns.")
observations.append(f"The target column is 'isFraud', where 1 represents fraud and 0 represents normal transaction.")
observations.append(f"The dataset contains {fraud_count} fraud transactions and {normal_count} normal transactions.")
observations.append(f"Fraud transactions represent only {(fraud_count / len(df)) * 100:.4f}% of the dataset, confirming class imbalance.")
observations.append("The dataset contains transaction types such as PAYMENT, TRANSFER, CASH_OUT, CASH_IN, and DEBIT.")
observations.append("Missing value check shows whether cleaning is required before modeling.")
observations.append("The columns nameOrig and nameDest are high-cardinality ID columns and may not be directly useful for model training.")
observations.append("The isFlaggedFraud column must be handled carefully because it may contain rule-based fraud information.")
observations.append("Further EDA is required to understand fraud patterns by transaction type, amount, and balance changes.")

for i, obs in enumerate(observations, start=1):
    print(f"{i}. {obs}")

1. The dataset was loaded successfully from Google Drive.
2. The dataset contains 6362620 rows and 11 columns.
3. The target column is 'isFraud', where 1 represents fraud and 0 represents normal transaction.
4. The dataset contains 8213 fraud transactions and 6354407 normal transactions.
5. Fraud transactions represent only 0.1291% of the dataset, confirming class imbalance.
6. The dataset contains transaction types such as PAYMENT, TRANSFER, CASH_OUT, CASH_IN, and DEBIT.
7. Missing value check shows whether cleaning is required before modeling.
8. The columns nameOrig and nameDest are high-cardinality ID columns and may not be directly useful for model training.
9. The isFlaggedFraud column must be handled carefully because it may contain rule-based fraud information.
10. Further EDA is required to understand fraud patterns by transaction type, amount, and balance changes.

In [32]:
# ---------------------------------------------------------
# Step 32: Save Data Understanding Report
# ---------------------------------------------------------
# We save the key observations from this notebook into a text
# file inside the reports folder.

os.makedirs(REPORTS_DIR, exist_ok=True)

report_path = os.path.join(REPORTS_DIR, "01_data_understanding_report.txt")

with open(report_path, "w") as file:
    file.write("UPI Shield AI — Data Understanding Report\n")
    file.write("=" * 50 + "\n\n")

    file.write("Dataset Shape:\n")
    file.write(f"Rows: {df.shape[0]}\n")
    file.write(f"Columns: {df.shape[1]}\n\n")

    file.write("Column Names:\n")
    for col in df.columns:
        file.write(f"- {col}\n")

    file.write("\nMissing Values:\n")
    file.write(str(df.isnull().sum()))
    file.write("\n\n")

    file.write("Duplicate Records:\n")
    file.write(str(duplicate_count))
    file.write("\n\n")

    file.write("Fraud Class Distribution:\n")
    file.write(str(fraud_summary))
    file.write("\n\n")

    file.write("Transaction Type Distribution:\n")
    file.write(str(transaction_type_summary))
    file.write("\n\n")

    file.write("Fraud by Transaction Type:\n")
    file.write(str(fraud_by_type))
    file.write("\n\n")

    file.write("Initial Observations:\n")
    for i, obs in enumerate(observations, start=1):
        file.write(f"{i}. {obs}\n")

print("Data understanding report saved successfully.")
print("Report path:", report_path)

Data understanding report saved successfully.
Report path: /content/drive/MyDrive/UPI-Shield-AI-Transaction-Risk-Scoring/reports/01_data_understanding_report.txt

In [33]:
# ---------------------------------------------------------
# Step 33: Final Notebook Summary
# ---------------------------------------------------------
# This final summary confirms that Notebook 1 is completed.

print("Notebook 1: Data Understanding completed successfully.")

print("\nKey Outputs:")
print("- Dataset loaded successfully")
print("- Dataset structure analyzed")
print("- Missing values checked")
print("- Duplicate records checked")
print("- Fraud class imbalance confirmed")
print("- Transaction types analyzed")
print("- Initial observations saved")

print("\nNext Notebook:")
print("02_eda_visualization.ipynb")

Notebook 1: Data Understanding completed successfully.

Key Outputs:
- Dataset loaded successfully
- Dataset structure analyzed
- Missing values checked
- Duplicate records checked
- Fraud class imbalance confirmed
- Transaction types analyzed
- Initial observations saved

Next Notebook:
02_eda_visualization.ipynb

# Notebook 1 Summary

In this notebook, we successfully completed the data understanding phase.

## Key Findings

1. The dataset contains online/mobile money transaction records.
2. The target column is `isFraud`.
3. The dataset is highly imbalanced because fraud transactions are very rare compared to normal transactions.
4. Transaction type, amount, and balance-related columns are important for fraud detection.
5. The columns `nameOrig` and `nameDest` are high-cardinality ID columns and may not be directly useful for simple model training.
6. The column `isFlaggedFraud` should be handled carefully because it may contain rule-based fraud information.
7. Further EDA is required to understand fraud patterns in detail.

## Next Step

The next notebook will be:

`02_eda_visualization.ipynb`

In that notebook, we will create visualizations to understand fraud patterns by transaction type, amount, and balance behavior.